POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username":"sewalew.setotaw",
    "password":"123456"
}

###

GET http://127.0.0.1:8000/api/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5MDkyMTg1LCJpYXQiOjE3NTkwODg1ODUsImp0aSI6ImU2N2JlNDc0MjBlMzRmODA5Yjk3YTFmZTkwNGVkOGE2IiwidXNlcl9pZCI6IjY1YjMyYWYzLTIwNWYtNGVlZS1iNThjLTY1YTlmOGNhZjU0ZCJ9.uJhNrxndhzyaqelfJUTgcMWmHyIVvjaZEEK6Uy7cvMY

###
GET http://127.0.0.1:8000/api/users/65b32af3-205f-4eee-b58c-65a9f8caf54d/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5MDc3NjY3LCJpYXQiOjE3NTkwNzQwNjcsImp0aSI6ImU4ZmUyMmEyNjM3NjQ0NDQ5YzQ2NWQzYmE5YjY4OGU0IiwidXNlcl9pZCI6IjY1YjMyYWYzLTIwNWYtNGVlZS1iNThjLTY1YTlmOGNhZjU0ZCJ9.HvE-EauGjMOKS_liLKEX9nacwFB6qQutVCdcTY2_eFU

###
POST http://127.0.0.1:8000/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4NzY3MzY2LCJpYXQiOjE3NTg3NjM3NjYsImp0aSI6ImQwYjUyYmY0OTA0MDRiZTViZTNhZmRkMTA4MjY4NjFiIiwidXNlcl9pZCI6IjY1YjMyYWYzLTIwNWYtNGVlZS1iNThjLTY1YTlmOGNhZjU0ZCJ9.NM4lm7bW_QqOjRc0WRiqVoqDBnj6RQAC-5A0gnjtXQI

{
    "name": "M-size T-shirt",
    "description": "M-size T-shirt",
    "price": "4500.00",
    "stock": 14,
    "category": "cb20265c-8179-48bb-9d06-9c6a2e6f5be9",
    "seller": "5ce267ae-1b7f-4b5c-9d0c-24ac13e478cc"
}