# Generated by Django 4.2.23 on 2025-09-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_alter_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
