# Generated by Django 5.2.6 on 2025-09-28 15:10

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_cartitem_cartitem_quantity_positive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Enter a valid Ethiopian phone number in the format +2519XXXXXXXX.'}, max_length=128, null=True, region='ET'),
        ),
    ]
